#Config for enemy randomizations
#lines marked with # are comments, editing them does nothing
################# ENEMY RANDOMIZATION #################


################# ENEMY TRAIT RANDOMIZATION #################

[traits]

# Trait change mode
# "none"      : traits are unchanged
# "swap"      : traits are globally swapped (ex: red -> black)
# "randomize" : each enemy gets a random trait
mode = "randomize"

# swap settings
specified_swaps = [                         # control trait swap if swap mode is selected, otherwise ignored
                                            # trait swaps in the format ["from_trait", "to_trait"], ie ["red", "black"] (red enemies all become black)
    ]

# randomize settings
keep_trait_amount = true                    # enemies keep their original number of traits (if false, they only get 1 trait)
always_new_trait = true                     # enemies will never randomize into their base trait

################# TRAIT GIMMICKS #################

[traits.gimmicks]
enabled = true                              # allows giving abilities/stat changes
                                            # disable this to make it just trait changes

[traits.gimmicks.black]
enabled = true
speed_boost = [
    [3,3],
    ["x1.8",15],                            # [boost,units with speed up to] x to mark a multiplier (default gives +3 speed to things 3 speed or less and 1.8x to things up to 8 speed)
    ["x1.5",1000],
    ]
kb_mult = 1.5                               # amount kb are mult by
rounds_down = false

[traits.gimmicks.red]
enabled = true
speed_mult = 0.8
kb_mult = 0.5
rounds_down = true

[traits.gimmicks.white]
enabled = true
whites_are_sage = true                      # sages all get white
sage_rework = true                          # nerfs sages effects and gives weird kb interactions

[traits.gimmicks.floating]
enabled = true
wave_immune_weight = 5                      # chooses 1 ability from a pool at weights given
surge_immune_weight = 5
counter_surge_weight = 5
wave_block_weight = 3
dual_ability_chance = 20  # 1-100

[traits.gimmicks.relic]
enabled = true
get_curse = true
get_weak_pierce = true                      # non ld 1 hit units get a portion of their damage as piercing damage
pierce_atk_percent = 10
pierce_range_percent = 5

[traits.gimmicks.zombie]
enabled = true
balanced = true                             # reworks weights so strong zombies get stronger revive/burrow while weak zombies get weak burrow/revive (entries earlier in the lists are considered stronger)
grant_revive = true
revive_frequency = 100                      #determines how many zombies have revive
revive_types = [
    [-1, 100, 30, 5],                       # [count (-1 for inf), revive at hp%, revive after, weight]
    [-1, 10, 200, 5],
    [3, 50, 90, 10],
    [1, 100, 300, 10],
    [1, 50, 240, 10],
    [1, 100, 900, 5],
    [2, 10, 30, 5],
    [1, 10, 180, 10],
]
grant_burrow = true
burrow_frequency = 70
burrow_types = [                            # put burrows weak enemies shouldnt get higher in this list
    [-1,1600,3],                            # [count, distance x 4, weight]
    [3,2400,3],
    [1,6000,6],
    [1,4000,10],
    [1,3000,10],
    [1,2000,10],
    [1,1000,5],
    ]

[traits.gimmicks.alien]
enabled = true                              # aliens get a random ability
freeze_weight = 5
slow_weight = 5
kb_weight = 5
weak_weight = 5
wave_weight = 2
surge_weight = 2
explode_weight = 0
crit_weight = 5
savage_weight = 5
lethal_weight = 4
base_des_weight = 5
multihit_weight = 3

starred_frequency = 30                      # base 30% of aliens are starred (cannot appear in eoc/itf/cotc if crystals are on)
warp_frequency = 60
barrier_frequency = 50

[traits.gimmicks.angel]
enabled = true
balanced = true                             # balanced makes hp/speed buffs half as effective on >2 mill hp enemies
speed_mult = 1.3
attack_mult = 0.8
health_mult = 1.3

[traits.gimmicks.aku]
enabled = true
shield_frequency = 50
death_frequency = 50
ds_ability_frequency = 20                   # some enemies will get an ability that only activates on death surge
ds_ability_is_mini = true

[traits.gimmicks.metal]
enabled = false                             # metals arent meant to exist so this does nothing

################# ENEMY EXCEPTIONS #################

[exceptions]  # these exceptions will change specific enemies
doge = true         # stops alien doge from making korea impossible
johnny = true       # makes johnny our mascot (sprite will be incorrect if false)
brollow = true      # makes brollow always fucked
squirrel = true     # angel squirrel is a menace to soccer
poultrio = false    # could make it like johnny but poul isnt out mascot

################# FORCE TRAITS #################

[force_traits]    # these exist to force certain enemies to be certain traits
tad_type_apk = false
dab_type_apk = false
amph_type_apk = false
ryelo_type_apk = false



[extras]
id_swap = false                             # swaps enemy id (ie those guys become doge)
swap_to_similar_enemy = true                # limits swap to only similar "strength" enemies
swap_ranges = [
    [1,10],                                 # feel free to add more groupings, numbers range from 1-30
    [11,20],                                # the smaller the groupings the more balanced itll be
    [21,30],
    ]                  

randomize_abilities = false                 # randomizes each enemies abilities (keeps number the same)
randomize_only_base_abilities = false       # only randomize abilities enemies normally have

randomize_god = true                        # literally just makes 3 random enemies god instead of normal gods













