# Randomizer config for The Battle Cats

[general]
# ENTER RANDOMIZATION SEED BELOW (if not, a random one will be chosen)
seed = 0


################# GAMEPLAY CHANGES #################

[gameplay]
remove_metals = true                    # literally removes metals from the game, recommended
give_metals_new_trait = true            # gives ex metals a trait
use_metal_rework = true                 # uses my ex metal rebalance
remove_behemoths = true
use_behemoth_rebalance = true           # uses my ex behemoth rebalance
preserve_old_zombies = true             # swaps zkiller and witch so old zombies can still burrow (makes sorting cats weird)
preserve_alien_magnifications = true    # buffs old aliens in itf and cotc to make them not piss easy
remove_itf_crystals = false             # removes itf crystals from the game (if false no new aliens can be in itf to make it not stupid)
remove_cotc_crystals = true             # removes cotc crystals from the game, recommended who likes these

[gameplay.unit_reworks]
rework_units = true                     # reworks ex metals and certain favoured units, theyre fun
courier = true                          # removes massive to stop it from killing an entire trait
jurassic = true
space = true
jumprope = true
hurricat = true
waitress = true
aku_researcher = true
backhoe = true
mint = true
punt = true
merc = true
capsule = true
racism_cow = true
reaper = true
million_dollar = true
cop = true
paladin = true
cat_clan = true
verbena = true
hayabusa = true
moneko = true
neneko = true
summer_neneko = true
new_year_neneko = true                  
valentine_neneko = true
easter_neneko = true
cmoneko = true


################# CAT COMBO CHANGES #################

[nyancombo]
RANDOMIZE_COMBOS = true
randomize_units = true                                  # randomize cat combo units
randomize_multipliers = true                            # randomize combo multiplier sizes (sm, M, L, XL, DOWN)
randomize_effects = true                                # randomize combo effects

[nyancombo.size]
CUSTOM_MULTIPLIER_WEIGHTS = true                        # If false, chooses between the 5 combo effect multipliers at equal chance  

# For each combo unit count ("1"–"5"), defines the weight of each effect size
# Higher value = higher chance of being selected
# Only used if CUSTOM_MULTIPLIER_WEIGHTS = true
"1" = { SM = 45, M = 25, L = 5, XL = 0, DOWN = 20 }                  
"2" = { SM = 35, M = 40, L = 10, XL = 0, DOWN = 15 }    
"3" = { SM = 10, M = 45, L = 35, XL = 5, DOWN = 5 }    
"4" = { SM = 0, M = 15, L = 65, XL = 15, DOWN = 5 }    
"5" = { SM = 0, M = 5, L = 70, XL = 25, DOWN = 0 } 

PRESERVE_COMBO_UNIT_COUNT = true                        # Combos stay at their original unit count
CUSTOM_UNIT_COUNT_WEIGHTS = false                       # If false, chooses between having 1-5 units at random

# Relative weights for choosing combo unit count (1–5)
# Higher value = higher chance of being selected        
# Only applied if CUSTOM_UNIT_COUNT_WEIGHTS = true
unit_count_weights = { "1" = 10, "2" = 25, "3" = 35, "4" = 20, "5" = 10 }


################# QUALITY OF LIFE CHANGES #################

[qol]
catfruit_changes = true
buff_normal_catfruit = true
xp_buffs = true
behemoth_cube_buff = true
enigma_buff = true
orb_enigmas_are_relic_aku = true
weekday_specials = true                         # replaces weekday stages with special tf stages
weekend_lils = true                             # replaces weekend stage with lil ticket farming stages
xp_stage_item_farming = true
shop_buff = true
cheaper_items = true
leadership_in_shop = true
ototo_helper_in_shop = true
cheap_catamin = true
units_3x_sell = true
free_orb_removal = true
mission_collab_special_tf_drop = false          #current doesnt work

[qol.stage_changes]
seasonals_in_sol = true                         # adds monthly and certain collab units to sol
collabs_as_advents = true                       # adds ^ true forms to advents
jubilee_always_epic = true
gstrange_buff = true
growing_aku_buff = true
growing_epic_buff = true
sol_xp_buff = true
megablitz_buff = true
colloseum_buff = true
material_stage_buff = true
proving_grounds_buff = true
hate_metal_hippoe_buff = true
siege_buff = true
facing_danger_buff = true
isle_of_treasure_buff = true
orb_stage_has_strong_massive_resist = true
orb_stage_has_ability_orb = true



################# MISC CHANGES #################

[funny]
youcan_warning = true
special_surprise = true